[[language]]
name = "powershell"
scope = "source.ps1"
file-types = ["ps1", "psm1"]
roots = [".git"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "powershell-editor-services" ]

[language-server.powershell-editor-services]
command = "pwsh"
args = ["-NoLogo", "-NoProfile", "-Command", "C:\\Users\\nf\\AppData\\Local\\PowerShellEditorServices\\PowerShellEditorServices\\Start-EditorServices.ps1 -BundledModulesPath C:\\Users\\nf\\AppData\\Local\\PowerShellEditorServices\\PowerShellEditorServices -SessionDetailsPath C:\\Users\\nf\\AppData\\Local\\PowerShellEditorServices\\PowerShellEditorServices.sessions.json -LogPath C:\\Users\\nf\\AppData\\Local\\PowerShellEditorServices\\PowerShellEditorServices.log -FeatureFlags @() -AdditionalModules @() -HostName helix -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal"]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
