[[language]]
name = "pwsh"
scope = "source.ps1"
roots = [".git"]
file-types = ["ps1"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "pwsh", args = ["-NoLogo", "-NoProfile", "-Command", "C:/Users/nf/recos/save/.bin/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath /usr/local/bin/powershell-es -SessionDetailsPath /usr/local/bin/powershell-es/powershell_es.sessions.json -LogPath /usr/local/bin/powershell-es/powershell_es.log -FeatureFlags @() -AdditionalModules @() -HostName helix -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal"] }